name: Build and Test

# This workflow runs for regular branch pushes and PRs,
# but NOT for tag pushes which are handled by the release.yml workflow.

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths-ignore:
      - ".gitignore"
      - ".github/**"
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - ".gitignore"
      - ".github/**"
      - "**/*.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for GitVersion
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "6.x"

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
          updateAssemblyInfo: true

      - name: Display GitVersion outputs
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Restore dependencies
        run: dotnet restore src/

      - name: Build
        run: dotnet build src/ --configuration Release --no-restore /p:TreatWarningsAsErrors=false

      - name: Run tests
        run: dotnet test src/ --configuration Release --no-build --verbosity normal

      - name: Pack NuGet package
        run: |
          echo "Packing SnapcastClient with version ${{ steps.gitversion.outputs.nuGetVersion }}"
          dotnet pack src/SnapcastClient/SnapcastClient.csproj --configuration Release --no-build \
            -o ./artifacts \
            /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }}

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg
          retention-days: 7
