name: Publish NuGet Package

on:
  push:
    branches: [ mainline ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ mainline ]

# Add explicit permissions for the workflow
permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/
      
    - name: Build
      run: dotnet build src/ --no-restore --configuration Release
      
    - name: Test
      run: dotnet test src/ --no-build --configuration Release --verbosity normal

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/mainline' || startsWith(github.ref, 'refs/tags/v'))
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/
      
    - name: Build
      run: dotnet build src/ --no-restore --configuration Release
      
    - name: Pack
      run: dotnet pack src/snapcast-net/snapcast-net.csproj --no-build --configuration Release --output ./packages
      
    - name: Publish to GitHub Packages
      run: dotnet nuget push ./packages/*.nupkg --source "https://nuget.pkg.github.com/metaneutrons/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
